### ISSUE TITLE
git driver is broken using private key

### ISSUE THREAD

**Issue by consolibyte** [cappyzawa/romver-resource#1]
It looks like `romver` suffers from the same private key bug that `semver` suffers from. 

More details (and work-arounds) here: https://github.com/concourse/semver-resource/issues/79

**Comment by cappyzawa** [comment]
@consolibyte Thanks your reporting 👍 
And sorry for the late notice.

I'll fix this soon base on the information you gave me.

**Comment by cappyzawa** [comment]
I have fixed this(https://github.com/cappyzawa/romver-resource/commit/8f4a1cbf9bfc8ec38a7da0060d6385bac681e1fb) and published a new image ([Image Layer Details \- cappyzawa/romver\-resource:0\.0\.11 \- sha256:5bffafd29c99803dd1658d1ec6ea6eec0c0a9dbfd821373a89912ec70ee006dd \- Docker Hub](https://hub.docker.com/layers/cappyzawa/romver-resource/0.0.11/images/sha256-5bffafd29c99803dd1658d1ec6ea6eec0c0a9dbfd821373a89912ec70ee006dd?context=explore))
